# Generated by Django 4.2 on 2025-09-03 06:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التحليل')),
                ('app_name', models.CharField(default='singletest', max_length=100)),
                ('description', models.CharField(choices=[('hematology', 'hematology'), ('chemistry', 'chemistry'), ('bactrology', 'bactrology'), ('imunity', 'imunity'), ('histology', 'histology'), ('parasitology', 'parasitology')], default='hematology', max_length=20, verbose_name='الحالة')),
                ('subclass', models.TextField(blank=True, verbose_name='الفرع')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('normal_value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية الدنيا')),
                ('normal_value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية العليا')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تحليل فردي',
                'verbose_name_plural': 'التحاليل الفردية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المجموعة')),
                ('app_name', models.CharField(default='paneltest', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الإجمالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tests', models.ManyToManyField(to='lab.individualtest', verbose_name='التحاليل المتضمنة')),
            ],
            options={
                'verbose_name': 'مجموعة تحاليل',
                'verbose_name_plural': 'مجموعات التحاليل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('individual_tests', models.ManyToManyField(blank=True, to='lab.individualtest', verbose_name='التحاليل الفردية')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient', verbose_name='المريض')),
                ('test_groups', models.ManyToManyField(blank=True, to='lab.testgroup', verbose_name='مجموعات التحاليل')),
            ],
            options={
                'verbose_name': 'طلب تحليل',
                'verbose_name_plural': 'طلبات التحاليل',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PrintedReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطباعة')),
                ('report_type', models.CharField(default='patient_report', max_length=50, verbose_name='نوع التقرير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient', verbose_name='المريض')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='طبع بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير مطبوع',
                'verbose_name_plural': 'التقارير المطبوعة',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='TestGroupResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testgroup', verbose_name='مجموعة التحاليل')),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testrequest', verbose_name='طلب التحليل')),
            ],
            options={
                'verbose_name': 'نتيجة مجموعة تحاليل',
                'verbose_name_plural': 'نتائج مجموعات التحاليل',
                'ordering': ['-result_date'],
                'unique_together': {('test_request', 'test_group')},
            },
        ),
        migrations.CreateModel(
            name='IndividualTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('status', models.CharField(choices=[('normal', 'طبيعي'), ('high', 'مرتفع'), ('low', 'منخفض'), ('abnormal', 'غير طبيعي')], max_length=20, verbose_name='الحالة')),
                ('result_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('individual_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.individualtest', verbose_name='التحليل')),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.testrequest', verbose_name='طلب التحليل')),
            ],
            options={
                'verbose_name': 'نتيجة تحليل فردي',
                'verbose_name_plural': 'نتائج التحاليل الفردية',
                'ordering': ['-result_date'],
                'unique_together': {('test_request', 'individual_test')},
            },
        ),
    ]
