# Generated by Django 4.2 on 2025-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_patient_address_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
    ]
