# Generated by Django 4.2 on 2025-09-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_testgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtest',
            name='subclass',
            field=models.TextField(blank=True, verbose_name='subclass'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient', to_field='barcode', verbose_name='المريض'),
        ),
    ]
