# Generated by Django 4.2 on 2025-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_individualtest_subclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtestresult',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'طبيعي'), ('high', 'مرتفع'), ('low', 'منخفض'), ('abnormal', 'غير طبيعي')], max_length=20, verbose_name='الحالة'),
        ),
    ]
