# Generated by Django 4.2 on 2025-09-08 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_individualtestresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='اسم الجهاز')),
                ('device_id', models.CharField(max_length=100, verbose_name='معرف الجهاز')),
                ('result', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نتيجة التحليل')),
                ('insert_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الإدخال')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient', to_field='barcode', verbose_name='المريض')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.individualtest', verbose_name='التحليل')),
            ],
            options={
                'verbose_name': 'نتيجة جهاز',
                'verbose_name_plural': 'نتائج الأجهزة',
                'ordering': ['-insert_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceresult',
            constraint=models.UniqueConstraint(fields=('device_id', 'barcode', 'test'), name='unique_device_barcode_test'),
        ),
    ]
