# Generated by Django 4.2 on 2025-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_deviceresult_deviceresult_unique_device_barcode_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceresult',
            name='unique_device_barcode_test',
        ),
        migrations.RemoveField(
            model_name='deviceresult',
            name='device_id',
        ),
        migrations.AddField(
            model_name='deviceresult',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddConstraint(
            model_name='deviceresult',
            constraint=models.UniqueConstraint(fields=('barcode', 'test'), name='unique_device_barcode_test'),
        ),
    ]
