# Generated by Django 4.2 on 2025-09-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_deviceresult_unique_device_barcode_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceresult',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النتيجة'),
        ),
    ]
