# Generated by Django 4.2 on 2025-09-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_deviceresult_insert_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceresult',
            name='unique_device_barcode_test',
        ),
        migrations.AddConstraint(
            model_name='deviceresult',
            constraint=models.UniqueConstraint(fields=('barcode', 'test', 'insert_datetime'), name='unique_device_barcode_test_time'),
        ),
    ]
