# Generated by Django 4.2 on 2025-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_remove_deviceresult_unique_device_barcode_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualtest',
            options={'ordering': ['display_order'], 'verbose_name': 'تحليل فردي', 'verbose_name_plural': 'التحاليل الفردية'},
        ),
        migrations.AddField(
            model_name='individualtest',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
