# Generated by Django 4.2 on 2025-09-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_individualtest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtest',
            name='subclass',
            field=models.CharField(blank=True, max_length=100, verbose_name='subclass'),
        ),
        migrations.AlterField(
            model_name='individualtestresult',
            name='value',
            field=models.CharField(max_length=100, verbose_name='القيمة'),
        ),
    ]
