# Generated by Django 4.2 on 2025-09-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0011_alter_individualtest_subclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtestresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualtestresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_modified', to=settings.AUTH_USER_MODEL, verbose_name='اخر تغديل بواسطة'),
        ),
        migrations.AddField(
            model_name='individualtestresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='individualtestresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة'),
        ),
        migrations.AlterField(
            model_name='individualtestresult',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'طبيعي'), ('high', 'مرتفع'), ('low', 'منخفض'), ('abnormal', 'غير طبيعي'), ('n/a', 'غير محدد')], max_length=20, verbose_name='الحالة'),
        ),
    ]
