# Generated by Django 4.2 on 2025-09-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_individualtestresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtest',
            name='normal_value_max',
        ),
        migrations.RemoveField(
            model_name='individualtest',
            name='normal_value_min',
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_f',
            field=models.TextField(blank=True, null=True, verbose_name='القيم الطبيعية نساء'),
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_m',
            field=models.TextField(blank=True, null=True, verbose_name='القيم الطبيعية رجال'),
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_max_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية العليا نساء'),
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_max_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية العليا رجال'),
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_min_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية الدنيا نساء'),
        ),
        migrations.AddField(
            model_name='individualtest',
            name='normal_value_min_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة الطبيعية الدنيا رجال'),
        ),
    ]
