# Generated by Django 4.2 on 2025-09-22 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0013_remove_individualtest_normal_value_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtestresult',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_modified', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='app_name',
            field=models.CharField(default='paneltest', max_length=100, verbose_name='اسم في الباركود'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'تم حذف احد النتائج')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='DeviceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isordersent', models.BooleanField(default=True, verbose_name='نشط')),
                ('insert_datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('accession_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient', to_field='barcode', verbose_name='المريض')),
                ('online_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.individualtest', verbose_name='التحليل')),
            ],
            options={
                'verbose_name': 'طلب جهاز',
                'verbose_name_plural': 'طلبات الأجهزة',
                'ordering': ['-insert_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceorder',
            constraint=models.UniqueConstraint(fields=('accession_number', 'online_test'), name='unique_patient_test_order'),
        ),
    ]
